[package]
name = "OG-Raid-Manager"
version = "0.1.0"
authors = [ "Lance Wallis <walance@pvas.me>"]
edition = "2021"

[[bin]]
name = "raid-manager"
path = "raid-manager.rs"

[dependencies]
serenity = "0.12.1"
poise = "0.6.1"
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }

fusion-util = { path = "../../lib/fusion-util" }
