[package]
name = "OG-Raid-Manager"
version = "0.1.0"
authors = [ "Lance Wallis <walance@pvas.me>"]
edition = "2021"

[[bin]]
name = "raid-manager"
path = "raid-manager.rs"

[dependencies]
serenity = { version = "0.12.1", default-features = true }
poise = { version = "0.6.1", default-features = true}
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread"] }

serde = "1.0.197"
serde_json = "1.0.115"
futures = "0.3.30"
futures-executor = "0.3.30"

fusion-util = { path = "../../lib/fusion-util" }
